In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [7]:
#define vocabluary size
voc_Size=10000

In [8]:
#one hot encoding
one_hot_rep=[one_hot(words,voc_Size)for words in sent]
one_hot_rep

[[6001, 2385, 9586, 5053],
 [6001, 2385, 9586, 680],
 [6001, 2161, 9586, 6843],
 [3354, 1563, 2052, 6632, 3212],
 [3354, 1563, 2052, 6632, 3374],
 [3366, 6001, 4160, 9586, 1710],
 [6715, 5674, 631, 6632]]

In [11]:
#word embedding layers
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [12]:
import numpy as np

In [14]:
sent_length=8
embedded_docs=pad_sequences(one_hot_rep,padding="pre",maxlen=sent_length)

embedded_docs

array([[   0,    0,    0,    0, 6001, 2385, 9586, 5053],
       [   0,    0,    0,    0, 6001, 2385, 9586,  680],
       [   0,    0,    0,    0, 6001, 2161, 9586, 6843],
       [   0,    0,    0, 3354, 1563, 2052, 6632, 3212],
       [   0,    0,    0, 3354, 1563, 2052, 6632, 3374],
       [   0,    0,    0, 3366, 6001, 4160, 9586, 1710],
       [   0,    0,    0,    0, 6715, 5674,  631, 6632]])

In [15]:
#feature representation
dim=10

In [18]:
model=Sequential()
model.add(Embedding(voc_Size,dim,input_length=sent_length))
model.compile('adam','mse')

c:\Machine_Learning\Deep Learning\ANN_classification\venv\Lib\site-packages\keras\src\layers\core\embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [19]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [20]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 866ms/step


array([[[ 0.04498962,  0.03342653, -0.03232105,  0.0398738 ,
         -0.0298817 ,  0.04936837, -0.02773627, -0.03329398,
         -0.00188667,  0.03320481],
        [ 0.04498962,  0.03342653, -0.03232105,  0.0398738 ,
         -0.0298817 ,  0.04936837, -0.02773627, -0.03329398,
         -0.00188667,  0.03320481],
        [ 0.04498962,  0.03342653, -0.03232105,  0.0398738 ,
         -0.0298817 ,  0.04936837, -0.02773627, -0.03329398,
         -0.00188667,  0.03320481],
        [ 0.04498962,  0.03342653, -0.03232105,  0.0398738 ,
         -0.0298817 ,  0.04936837, -0.02773627, -0.03329398,
         -0.00188667,  0.03320481],
        [ 0.03170779,  0.04587705,  0.04300989, -0.04243177,
         -0.02097727,  0.02214973,  0.03058774, -0.04498308,
          0.01663505, -0.00690139],
        [ 0.04712835,  0.03200981, -0.03985429,  0.03344608,
         -0.0116887 , -0.03685932,  0.04371872, -0.04256951,
         -0.01315379, -0.03411724],
        [ 0.00324484,  0.02699493,  0.01160041,  0.0

In [22]:
embedded_docs[0]

array([   0,    0,    0,    0, 6001, 2385, 9586, 5053])